### ISSUE TITLE
Could not find a matching version of package

### ISSUE THREAD

**Issue by openstudio-one** [ramazancetinkaya/mysql-backup#10]
The following error is returned on `composer require ramazancetinkaya/mysql-backup`

> Installation failed, deleting ./composer.json.
> 
> In RequireCommand.php line 225:
>                                                                                                  
>   No composer.json present in the current directory (./composer.json), this may be the cause of  
>    the following exception.                                                                      
>                                                                                                  
> 
> In PackageDiscoveryTrait.php line 376:
>                                                                                                  
>   Could not find a matching version of package ramazancetinkaya/mysql-backup. Check the package  
>    spelling, your version constraint and that the package is available in a stability which mat  
>   ches your minimum-stability (stable).

**Comment by ramazancetinkaya** [comment]
I would like to inform you that the specified issue has been resolved. Could you please provide feedback after retrying the process?

**Comment by openstudio-one** [comment]
@ramazancetinkaya I still get the same issue I am afraid
<img width="732" alt="error" src="https://github.com/ramazancetinkaya/mysql-backup/assets/152746674/4c343ea0-a649-4618-bbbf-b5b28e7995b2">

**Comment by ramazancetinkaya** [comment]
@openstudio-one

Which version of PHP are you currently using?

**Comment by openstudio-one** [comment]
php 8.3.1 
<img width="476" alt="Screenshot 2023-12-28 alle 12 24 31" src="https://github.com/ramazancetinkaya/mysql-backup/assets/152746674/ca84e254-5074-4778-ad0d-ae60b3fafda5">

**Comment by ramazancetinkaya** [comment]
@openstudio-one

Could you please try the process again? If it doesn't work, I'll try another solution.

**Comment by openstudio-one** [comment]
@ramazancetinkaya yes, it worked now! thanks!

<img width="603" alt="Screenshot 2023-12-28 alle 14 01 09" src="https://github.com/ramazancetinkaya/mysql-backup/assets/152746674/b216f4f7-2f85-4824-9287-280693ad865a">

**Comment by ramazancetinkaya** [comment]
Thank you for your patience. I hope this project proves useful to you.
